name: test

on:
  - push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - run: npx serve &
      - run: echo $!
      - run: ps
      - run: sleep 10
      - run: curl -i http://localhost:5000
